### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by Nowosad** [Bakaniko/foss4g2022-getting-started-rspatial#10]
@Bakaniko how should we mention packages in the text? I can think of three main options:

1. package (e.g., tmap)
2. {package} (e.g., {tmap})
3. **package** (e.g., **tmap**)

**Comment by Bakaniko** [comment]
@Nowosad, good question.
In 2019, I used {package}. Lately I use `package` but I think it can create confusion with code.

I agree it should be emphasized in a way but I don't have any preferences

**Comment by Nowosad** [comment]
I would suggest using {package} here
