### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by Nowosad** [Bakaniko/foss4g2022-getting-started-rspatial#12]
The `images/venn-clip-1.png` is missing in https://bakaniko.github.io/foss4g2022-getting-started-rspatial/manipulating-vector-data.html#centroids

**Comment by nicolas-roelandt** [comment]
fixed by [#cb97cf57](https://github.com/Bakaniko/foss4g2022-getting-started-rspatial/blob/cb97cf57215b63891087606d52546d33a775bafd/05-manipulating-vector-data.Rmd#L274-L278)
