### ISSUE TITLE
Error in 06-manipulating-raster-data-38

### ISSUE THREAD

**Issue by nicolas-roelandt** [Bakaniko/foss4g2022-getting-started-rspatial#13]
@Nowosad , I got an error with a chunk in chapter 5:

``` r
srtm_utm_m <- mask(srtm_utm_c, zion)
#>Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘mask’ for signature ‘"SpatRaster", "sf"’
```

I restarted the R session and run the whole chapter but the error is still there. Any ideas ?

**Comment by Nowosad** [comment]
You need to have the most current {terra} version -- see https://github.com/rspatial/terra/issues/89 for the context

**Comment by nicolas-roelandt** [comment]
Oh ! Thanks, I didn't think my installation was **that** old... ;)

**Comment by Nowosad** [comment]
The partial {sf} support was added a few weeks ago in {terra}.

**Comment by nicolas-roelandt** [comment]
That will be a bleeding edge workshop ! ;)
Add to manual remove {terra] 1.5.x but it works. Thanks !
