### ISSUE TITLE
nz_ports.gpkg The file doesn't seem to exist.

### ISSUE THREAD

**Issue by xuefliang** [Bakaniko/foss4g2022-getting-started-rspatial#14]
nz_ports <- read_sf("data/nz_ports.gpkg")
Error: Cannot open "data/nz_ports.gpkg"; The file doesn't seem to exist.

where can i download this dataset

**Comment by Nowosad** [comment]
The file is here -- https://github.com/Bakaniko/foss4g2022-getting-started-rspatial/tree/main/data

**Comment by xuefliang** [comment]
thinks
